# Usa un'immagine base Python ufficiale
FROM python:3.9-slim

# Imposta la directory di lavoro all'interno del container
WORKDIR /usr/src/app

# Copia il file dei requisiti e installa le dipendenze
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia il resto del codice dell'applicazione (incluso server.py)
COPY . .

# Espone la porta su cui il server resta in ascolto
EXPOSE 8080

# Comando per avviare il server
CMD [ "python", "server.py" ]
